CREATE TABLE Ships(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	TypeId INT NOT NULL FOREIGN KEY REFERENCES [dbo].[Types](Id),
	DirectionId INT NOT NULL FOREIGN KEY REFERENCES [dbo].[Directions](Id),
	[Length] INT NOT NULL,
	Speed INT NOT NULL DEFAULT(1),
	[Range] INT NOT NULL DEFAULT(1),
)
GO