CREATE TABLE Positions(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	QuadrantId INT NOT NULL FOREIGN KEY REFERENCES [dbo].[Quadrants](Id),
	PointId INT NOT NULL FOREIGN KEY REFERENCES [dbo].[Points](Id)
)
GO